### ISSUE TITLE
Highlight Permissions

### ISSUE THREAD

**Issue by codephobia** [clarkio/vscode-twitch-highlighter#1]
Store the username of who highlighted a line, so that they are allowed to unhighlight one of their highlights. This will allow users to self fix a highlight that was done incorrectly, but not randomly unhighlight other users highlighting.

**Comment by clarkio** [comment]
Thanks for adding the @codephobia.

This was completed in #17 and specifically here: https://github.com/clarkio/vscode-twitch-highlighter/pull/17/files#diff-45327f86d4438556066de133327f4ca2R180

We'll add the ability to unhighlight one's own highlight via a separate issue built off of #7
