### ISSUE TITLE
Nothing happens when clicking "Disconnected"

### ISSUE THREAD

**Issue by brylie** [clarkio/vscode-twitch-highlighter#105]
Clicking "Disconnected" doesn't open the pop-up, so I can't configure the authentication.

**To Reproduce**
1. Install Twitch Highlighter 0.2.2
2. Click on 'Disconnected'
3. Nothing happens

**Expected behavior**
> After clicking it, you'll see a notification that the extension is missing Twitch Credentials.

**Screenshots**

**VSCode Version**
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-13-generic

**Comment by parithon** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/364f3249-cd31-414f-ab2e-b486e275bf91-b427cfda-a7f5-497f-a483-1061dc3d44a5-v1.png?transparent=1&palette=1&width=246)

Unfortunately, I am not able to reproduce this bug. Can you try to manually set the credentials by opening your palette (CTRL+SHIFT+P) and type '>Twitch Highlighter: **Set Token**'. Additionally, you can also try to connect by using '>Twitch Highlighter: **Start Listening to Chat**'

**Comment by brylie** [comment]
K, I'll try that.

**Comment by brylie** [comment]
When I try the above steps, I get an error:

![Screenshot_20190510_214628](https://user-images.githubusercontent.com/17307/57549766-19068d00-736d-11e9-8037-439b9417d4dc.png)

Is there a file that the plugin may be trying to overwrite? Perhaps the file doesn't exist, or I need to change permissions?

**Comment by parithon** [comment]
I'll try to do a little more research on this issue. Can you tell me which Linux OS you're currently using?

**Comment by brylie** [comment]
Kubuntu 19.04

**Comment by parithon** [comment]
I've narrowed the issue down to the **node keytar** module; it requires **gnome-keyring** which isn't installed by default on Kubuntu, or any non-gnome UI variants of Linux.

You can solve this problem by installing **gnome-keyring**.

```bash
sudo apt install gnome-keyring
```

![bitmoji](https://render.bitstrips.com/v2/cpanel/81566a78-7669-403b-be7f-7a25399bcf8f-b427cfda-a7f5-497f-a483-1061dc3d44a5-v1.png?transparent=1&palette=1&width=246)

**Comment by brylie** [comment]
Jep, that was the issue! Quite a tricky one to diagnose :-)

**Comment by brylie** [comment]
Jep, that was the issue! Thank you for following up and helping me resolve it :-)
