### ISSUE TITLE
Cannot Generate token when using Twitch Chat OAuth Token Generator

### ISSUE THREAD

**Issue by PatPat1567** [clarkio/vscode-twitch-highlighter#108]
**Describe the bug**
When trying to go out to https://www.twitchapps.com/tmi/ in order to get a token for logging in, I get the following error. 

![image](https://user-images.githubusercontent.com/41209202/59170615-17afb800-8b05-11e9-8a64-e850acb24d54.png)

**To Reproduce**
1. Connect the "Twitch Chat OAuth Token Generator" inside Twitch
2. Go to https://www.twitchapps.com/tmi/

**Expected behavior**
Receive a token that can be entered into the highlighter for connecting to Twitch. 

**Screenshots**
See above

**VSCode Version**
0.2.2

**Comment by clarkio** [comment]
@PatPat1567 I'm not seeing an error when I go to the link. You should see a big blue button that says "Connect"

Here's what I'm seeing:
![image](https://user-images.githubusercontent.com/6265396/65634772-f4722100-dfac-11e9-890e-7780a88efb45.png)

Do you maybe have a browser extension hiding/removing it or something?

**Comment by clarkio** [comment]
@PatPat1567 with the new changes from #112 could you see if you are able to successfully connect everything?

**Comment by PatPat1567** [comment]
Sorry for the delay in response. Yes, I was able to get connected now.
