### ISSUE TITLE
Extension setting to customize highlight

### ISSUE THREAD

**Issue by matjaz321** [clarkio/vscode-twitch-highlighter#11]
### PROBLEM
- There is currently no option to customize highlight(color, border width, opacity etc.)
### PROPOSED SOLUTION
- Create settings for highlight color, border width, opacity

Propose some additional settings if you have some ideas.

**Comment by clarkio** [comment]
Added in https://github.com/clarkio/vscode-twitch-highlighter/pull/36

**Comment by clarkio** [comment]
Thank you for this suggestion btw @matjaz321
