### ISSUE TITLE
Could be great to have comment on the line

### ISSUE THREAD

**Issue by yoannfleurydev** [clarkio/vscode-twitch-highlighter#12]
I do not know if it is possible with VS Code, but it could be great to have the following:

* User input in Twitch chat : `!line 9 A comment`
* VS Code highlight the line 9 and on hover we can see the comment `A comment`.

**Comment by danielpomas** [comment]
Or show the comment with codelens above the line

**Comment by twhitson** [comment]
I think it would be great to have the ability to add comments to a line when highlighted. It could be rendered out similar to how the GitLens extension displays the most recent commit on that line.

See: https://github.com/eamodio/vscode-gitlens

**Comment by clarkio** [comment]
Thanks @yoannfleurydev for opening this issue and everyone that has provided input as well. We've now implemented this to show the comment on hover. We're open to looking into other ways of showing the comments such as the suggested codelens approach in the future.

It has now been added in #68. The plan is to publish this in version [0.1.5](https://github.com/clarkio/vscode-twitch-highlighter/milestone/3)

**Comment by clarkio** [comment]
Also, as @parithon mentioned on stream today, it might not be best to show these comments in a codelens type view since that will automatically be visible and we may not want to show inappropriate comments. Having them "hidden" in the hover view helps prevent this we thinks 😄
