### ISSUE TITLE
Additional arguments to select what kind of highlighting

### ISSUE THREAD

**Issue by bnb** [clarkio/vscode-twitch-highlighter#13]
Enable users to pass additional arguments to denote what they're trying to communicate:

Highlight:
```
!line 1
```

Error/bug:
```
!line 1 bug
```

Addition:
```
!line 1 add
```

**Comment by clarkio** [comment]
Thanks for opening this issue @bnb. It has now been added in #68. The plan is to publish this in version [0.1.5](https://github.com/clarkio/vscode-twitch-highlighter/milestone/3)
