### ISSUE TITLE
Publish extension to open-vsx

### ISSUE THREAD

**Issue by micheelengronne** [clarkio/vscode-twitch-highlighter#134]
Can you publish this extension to https://open-vsx.org/ also ?

It would make it available for vscodium users.

Thanks.

**Comment by clarkio** [comment]
Hey thanks for bringing this to my attention as I've not heard of that before. I'm open to exploring it more, understanding what it's about and how to publish an extension there.

**Comment by micheelengronne** [comment]
Sorry for the late answer. The doc gives the way to do: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by clarkio** [comment]
Hey @micheelengronne thanks for raising this issue and for your amazing patience for this to get implemented. It's now been published via PR #180 and can be found in the registry here: https://open-vsx.org/extension/clarkio/twitch-highlighter

**Comment by micheelengronne** [comment]
Thanks a lot !!
