### ISSUE TITLE
Create panel in sidebar to list highlights

### ISSUE THREAD

**Issue by lannonbr** [clarkio/vscode-twitch-highlighter#2]
You can create new panels in the sidebar with tree-views. It would be cool to be able to see the list of highlights and click on one to go focus on it.

Here's a sample of how to implement tree-views: https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample

**Comment by clarkio** [comment]
To expand upon this suggestion the list would be by twitch user handle, when expanded it would show the file and lines they highlighted.

From there the host can right-click and execute some list of actions (maybe unhighlight, dismiss, etc.)

**Comment by clarkio** [comment]
TODO: research another example panel that dynamically updates since we start with no highlighted lines and then need to show the list of highlights in the panel once they've been added to files.
