### ISSUE TITLE
Line highlight color match username color from twitch

### ISSUE THREAD

**Issue by talk2MeGooseman** [clarkio/vscode-twitch-highlighter#23]
The IRC information does provide a color attribute that the user has set on Twitch, it be cool to have that be set as the highlight color of the line they are setting.

**Comment by parithon** [comment]
I believe the last set decorator will take precedence... so, do we ensure the color used is the color from the first person who set the highlight or the last?

**Comment by clarkio** [comment]
I do like this suggestion but RuneW0lf from Twitter brought up a good point that the colors may not fit well depending on your VS Code theme and the twitch user's selected username color.

See here for more details: https://twitter.com/Runew0lf/status/1095446087811432448

I believe that's a good point and therefore don't think we should pursue this solution and instead stick with showing the username for now.

Thank you for taking the time to open this issue and contribute the idea to this project!
