### ISSUE TITLE
Clicking on highlight in menu creates a new file

### ISSUE THREAD

**Issue by FletcherCodes** [clarkio/vscode-twitch-highlighter#42]
1. Connect by clicking in the status bar
2. Open an existing file
3. Type `!line <LineNumber>` in Twitch chat
4. Scroll up/down so the line isn't visible
5. Open up the Twitch Highlighter menu
6. Click on the highlighted line

**Expected:** Move to the highlighted line
**Actual:** Created a new Untitled file

**Comment by clarkio** [comment]
Is there any way you can show a screen recording of what happened?

Here's what I'm seeing:
![issue-clip](https://user-images.githubusercontent.com/6265396/52169932-3db7ec80-270e-11e9-9cd0-c9973958a430.GIF)

**Comment by FletcherCodes** [comment]
![proof](https://user-images.githubusercontent.com/44245838/52178639-01959200-27c9-11e9-860a-9486acf0f770.gif)

**Comment by parithon** [comment]
This happens when you open individual files without a workspace (i.e. folder). I'm working on a fix.

**Comment by clarkio** [comment]
Resolved in #46 but not yet released. Will close this issue once released.

**Comment by FletcherCodes** [comment]
Working in 0.1.3
