### ISSUE TITLE
Can't Remove Highlight from menu

### ISSUE THREAD

**Issue by IAmFletcher** [clarkio/vscode-twitch-highlighter#44]
1. Connect by clicking in the status bar
2. Open an existing file
3. Type `!line <LineNumber>` in Twitch chat
4. Open up the Twitch Highlighter menu
5. Right-click a highlighted line and click `Remove Highlight`

**Expected:** Remove the highlight
**Actual:** Nothing

**Comment by clarkio** [comment]
Are you seeing an option for that in the menu? There shouldn't be one available at this time. Right now you can remove highlights in the following ways:

- Open Command Palette and type `twitch unhighlight`
    - Choose either the `unhighlight all` or `unhighlight by file and line option`
- Open the Highlighter view in the activity bar, right-click a highlight and choose `remove highlight`
- In the chat type `!line !<line number>` where <line number> is the line of the highlight you want to remove

**Comment by clarkio** [comment]
Resolved in #46 but not yet released. Will close this issue once released.
