### ISSUE TITLE
Does the nickname have to be lowercase?

### ISSUE THREAD

**Issue by clarkio** [clarkio/vscode-twitch-highlighter#47]
According to the Twitch API docs they say it has to be lowercase here: https://dev.twitch.tv/docs/irc/guide/

Maybe twitch-js lib already does this?

Investigate further.

**Comment by parithon** [comment]
I tested using uppercase and lowercase and everything in-between it was able to connect without issue. I also looked at the twitch-js module's wiki pages and it doesn't mention that the nickname needs to be lowercase.

**Comment by clarkio** [comment]
Ok cool, maybe the twitch-js package just handles this or the Twitch docs are out of date and no longer require that.

**Comment by FletcherCodes** [comment]
I assume twitch-js handles it as the Go Twitch IRC library I use had to ToLower the nickname too.

**Comment by clarkio** [comment]
Ok that makes sense. Since @parithon tested this out to validate the extension is good to go I'm going to close this. Thanks everyone.
