### ISSUE TITLE
Add multi-line highlighting 

### ISSUE THREAD

**Issue by mja00** [clarkio/vscode-twitch-highlighter#52]
Allow users to highlight multiple lines with !line 1-14 to get all the lines from 1 to 14 and then !line 1,5 to get lines 1 and 5.

**Comment by clarkio** [comment]
Thanks for opening this issue @mja00. It has now been fixed in #68. The plan is to publish this in version [0.1.5](https://github.com/clarkio/vscode-twitch-highlighter/milestone/3)
