### ISSUE TITLE
Contrast of highlight might need some work

### ISSUE THREAD

**Issue by corbob** [clarkio/vscode-twitch-highlighter#53]
Depending on the vscode theme in use, could actually make it harder to view contents.

Example:
![image](https://user-images.githubusercontent.com/30301021/52515604-9ede3500-2bd2-11e9-8ca2-45be7c8a5ad1.png)

**Comment by clarkio** [comment]
Appreciate the feedback. Check out the VS Code settings `Twitch Highlighter: Highlight Color` and `Twitch Highlighter: Highlight Border` to customize the look that works best for your theme.

Let me know if that helps. If it does we can close this issue then.

**Comment by corbob** [comment]
It helps, but only for that comment. If I hit a line that's not comment it opens up more contrast issues. What about adding a foreground color along with it so you don't have to worry about syntax highlighting making it hard to read?

**Comment by clarkio** [comment]
This is a great suggestion and I've completed some work that adds a new setting to adjust the font color within highlights. It's currently open for review in #55. I'll close this issue once it has been reviewed, merged and published in the 0.1.4 release.

**Comment by clarkio** [comment]
#55 has been merged now so we can close this and we'll publish a new release as version `0.1.4`. Expect these changes in that updated version
