### ISSUE TITLE
Use CHANGELOG.md

### ISSUE THREAD

**Issue by parithon** [clarkio/vscode-twitch-highlighter#58]
We need to start keeping track of changes in the CHANGELOG.md. The marketplace relies on this document for it's 'changelog' view.

![image](https://user-images.githubusercontent.com/8602418/52554407-971dbc80-2d9b-11e9-99c3-83f9d8d5ea5b.png)

**Comment by clarkio** [comment]
I'm on it. Thanks.

**Comment by clarkio** [comment]
Resolved in #59. Closing.
