### ISSUE TITLE
Unhighlight all lines when disconnecting a session

### ISSUE THREAD

**Issue by cmjchrisjones** [clarkio/vscode-twitch-highlighter#64]
When disconnecting a session, any lines stay highlighted, it would be good to have an option as to whether when disconnecting we want to un-highlight all of the lines currently highlighted.

**Comment by parithon** [comment]
Great feature request! Do you think we need it as an option or should we assume that if you disconnect you want the highlights to go away too?

**Comment by cmjchrisjones** [comment]
@parithon - I thought it would be a good idea to let the 'host' decide if they want to disconnect and un-highlight all, or just disconnect, EG in case they're disconnecting for some unplanned reason, but don't necessarily want to un-highlight any lines at that point in case they want to come back to it later. This came up during a @RamblingGeekUK stream which @clarkio was part of at the time we were talking about it - I just took this slightly further by mentioning giving the host the option as to decide what they wanted when ending the session :)

**Comment by clarkio** [comment]
This is addressed in #67 and will be released in version 0.1.5. Please let us know your thoughts on approach and if it works for you. Thanks for sharing this feedback!
