### ISSUE TITLE
Figure Out Linking for Versions like "Keep a Changelog"

### ISSUE THREAD

**Issue by clarkio** [clarkio/vscode-twitch-highlighter#73]
For some reason, the version tags aren't being linked when following the keep a changelog convention in our changelog.md.

See example: 
- Changelog version link: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#100---2017-06-20
- Result link: https://github.com/olivierlacan/keep-a-changelog/compare/v0.3.0...v1.0.0

**Comment by brettmillerb** [comment]
The markdown links in the change log example are all at the bottom. Sort of reference linking.

https://github.com/olivierlacan/keep-a-changelog/blame/master/CHANGELOG.md#L141

**Comment by parithon** [comment]
Thank you @brettmillerb for that information. I believe we were able to solve the issue on stream but we forgot to close out this comment. I'm going to close it now.
