### ISSUE TITLE
Set channel setting in settings screen instead of settings.json

### ISSUE THREAD

**Issue by SpyderHunter03** [clarkio/vscode-twitch-highlighter#74]
I think we should be able to enter the channel name in the settings screen (Ctrl + ,) instead of having to come into the settings.json screen.

**Comment by lampewebdev** [comment]
For multichannel setups:

### Requirement
As a user of the extension, I want to set up multiple channels.

### Possible implementation 
- Make it an array. Keep in mind that the 'string' now has to become array ['string'].
- Make it a comma separate list 'string, string`

**Comment by parithon** [comment]
@lampewebdev Are you using multiple channels from the same service, that is multiple channels on Twitch?

**Comment by SpyderHunter03** [comment]
@lampewebdev Where did that requirement come from?  And have you seen a valid use case IN ACTION that would use multichannel setup?  (I can come up with a valid use case but have not seen it being utilized)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by parithon** [comment]
I have published a PR that changes the `channels` setting from an array of string to a comma separated string value. This will allow you to edit the channels from the settings screen (CTRL+,)!

**Comment by clarkio** [comment]
Addressed in #76 and expected to be released in `0.1.5`. Thanks for this feedback @SpyderHunter03 and let us know if you have any further feedback on our approach to solving this issue.
