### ISSUE TITLE
Relative Lines

### ISSUE THREAD

**Issue by parithon** [clarkio/vscode-twitch-highlighter#80]
As pointed out on Twitter by [@finnurtest](https://twitter.com/finnurtest/status/1101636646234193920), if you configure vscode to use 'relative' line numbers it would be difficult for viewers to highlight lines accurately. Notice in the example snip below, my cursor is on line 21 but the numbers count up according to the distance from the cursor position. This is controlled by the vscode 'Line Numbers' setting.

![image](https://user-images.githubusercontent.com/8602418/53677299-82c63480-3c62-11e9-995d-7552c50281b1.png)

**Comment by clarkio** [comment]
I appreciate the work and effort on introducing support for relative line number users (especially for the vim community) but let's hold off on this for now. I think it may introduce some complexity into the project at this moment. What I think we may want to do for this is create a separate extension that focuses on relative line numbers.

Something else to consider is if there are enough programming streamers using relative numbers to drive more demand for this support.
