### ISSUE TITLE
No Way to delete Twitch Token

### ISSUE THREAD

**Issue by Digital-Tectonics** [clarkio/vscode-twitch-highlighter#86]
It would be nice to have the ability to delete the token, say if you miss entered it.
Like a shortcut when clicking on the icon.

**Comment by parithon** [comment]
There is, although it’s easy to miss since it uses remove password instead of remove token.

Open the command palette and look for the command Twitch Highlighter: Remove Password.

**Comment by clarkio** [comment]
@Digital-Tectonics and @parithon should we just move completely away from using "password" and instead use "token" since that's what it actually is?

**Comment by parithon** [comment]
Ok by me. I was going to do that initially but didn’t want to jar others that have seen password before...

Anthony Conrad
________________________________

**Comment by clarkio** [comment]
Addressed in #92 and will be released in v0.2.2
