### ISSUE TITLE
highlights dont increase in size, they only decrease

### ISSUE THREAD

**Issue by NickLarsen** [clarkio/vscode-twitch-highlighter#87]
```
!line 10
```

Then on line 10, add some space inside the highlight, and the highlight does not increase in size, it seems like it should always highlight the entire line even as it is edited.  To contrast this, the highlight does get smaller as you delete text from the line, and if you add text back in after deleting some, it will continue to increase back to the size it was when the highlight was created.

**Comment by parithon** [comment]
I believe this is a bug with vscode. Once we place the highlight decorator on the editor it is vscode that is handling the decorators decrease in size.

For us to handle the increase, we would need to 'watch' all changes on the editor and cross-reference those changes with all the highlights attached to the editor and increase the highlights size if it doesn't match the previous size after the change. I wonder what that'll do to performance.

**Comment by clarkio** [comment]
Closing as this has been fixed. Thanks again for the feedback 🙂👍
