### ISSUE TITLE
Sound Alert

### ISSUE THREAD

**Issue by RamblingGeekUK** [clarkio/vscode-twitch-highlighter#98]
Add the ability when a Line is highlighted to have a sound play to get the streamers attention.

**Comment by parithon** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/ae0e4745-5563-4c7e-b787-c4df00e4ac57-b427cfda-a7f5-497f-a483-1061dc3d44a5-v1.png?transparent=1&palette=1&width=246)

**Comment by parithon** [comment]
It appears the hard part about this request is the means to play the audio. Windows, as an example, doesn't come with a CLI based audio player therefore all of the NodeJS modules available to play sound will not work without the end user downloading a supported CLI based audio player first.

**Comment by clarkio** [comment]
Yea this is exactly the issue I've run into with my stream's chat bot - a consistent CLI based audio player that is cross platform. Maybe it's something we could work on in a separate project :)

I love the idea but is it cool if we close this @RamblingGeekUK?

**Comment by RamblingGeekUK** [comment]
Ok.  No Problem.
